# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: log4j2-pipeline
  path.config: "/usr/share/logstash/pipeline/log4j2-pipeline.conf"
  pipeline.workers: 3
- pipeline.id: file-log-pipeline
  path.config: "/usr/share/logstash/pipeline/logstash.conf"
  queue.type: persisted